---
- name: Install wordpress
  yum: name=wordpress state=present
  notify: restart php-fpm

- name: Copy nginx configuration for wordpress
  template: src=wordpress.conf.j2 dest=/etc/nginx/conf.d/wordpress.conf
  notify: restart nginx

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Set up WordPress config
  replace: dest=/etc/wordpress/wp-config.php regexp={{ item.regexp }} replace={{ item.replace }} backup=yes
  with_items:
    - { regexp: 'database_name_here', replace: '{{ wp_db_name }}' }
    - { regexp: 'username_here', replace: '{{ wp_db_user }}' }
    - { regexp: 'password_here', replace: '{{ wp_db_password }}' }
  no_log: True
